import os
from os import system
import time
from time import sleep
def bad():
    user=input("\033[0;35m [+] Type the name you want to extract from emails ==>> :")
    print("                                                  ")
    print("\033[1;91m }==>>{{{ Ctrl + C  'Exit' }}}<<=={ ")
    print("                                             ")
    print(user + "10@yahoo.com")
    sleep(1)
    print(user + "15@yahoo.com")
    sleep(1)
    print(user + "20@yahoo.com")
    sleep(1)
    print(user + "25@yahoo.com")
    sleep(1)
    print(user + "130@yahoo.com")
    sleep(1)
    print(user + "40@yahoo.com")
    sleep(1)
    print(user + "50@yahoo.com")
    sleep(1)
    print(user + "60@yahoo.com")
    sleep(1)
    print(user + "70@yahoo.com")
    sleep(1)
    print(user + "80@yahoo.com")
    sleep(1)
    print(user + "90@yahoo.com")
    sleep(1)
    print(user + "100@yahoo.com")
    sleep(1)
    print(user + "200@yahoo.com")
    sleep(1)
    print(user + "300@yahoo.com")
    sleep(1)
    print(user + "400@yahoo.com")
    sleep(1)
    print(user + "500@yahoo.com")
    sleep(1)
    print(user + "600@yahoo.com")
    sleep(1)
    print(user + "700@yahoo.com")
    sleep(1)
    print(user + "800@yahoo.com")
    sleep(1)
    print(user + "900@yahoo.com")
    sleep(1)
    print(user + "1000@yahoo.com")
    sleep(1)
    print(user + "2000@yahoo.com")
    sleep(1)
    print(user + "3000@yahoo.com")
    sleep(1)
    print(user + "4000@yahoo.com")
    sleep(1)
    print(user + "5000@yahoo.com")
    sleep(1)
    print(user + "6000@yahoo.com")
    sleep(1)
    print(user + "7000@yahoo.com")
    sleep(1)
    print(user + "8000@yahoo.com")
    sleep(1)
    print(user + "9000@yahoo.com")
    sleep(1)
    print(user + "-10@yahoo.com")
    sleep(1)
    print(user + "-20@yahoo.com")
    sleep(1)
    print(user + "-30@yahoo.com")
    sleep(1)
    print(user + "-40@yahoo.com")
    sleep(1)
    print(user + "-50@yahoo.com")
    sleep(1)
    print(user + "60@yahoo.com")
    sleep(1)
    print(user + "-70@yahoo.com")
    sleep(1)
    print(user + "-80@yahoo.com")
    sleep(1)
    print(user + "-90@yahoo.com")
    sleep(1)
    print(user + "-100@yahoo.com")
    sleep(1)
    print(user + "-200@yahoo.com")
    sleep(1)
    print(user + "-300@yahoo.com")
    sleep(1)
    print(user + "-400@yahoo.com")
    sleep(1)
    print(user + "-500@yahoo.com")
    sleep(1)
    print(user + "-600@yahoo.com")
    sleep(1)
    print(user + "-700@yahoo.com")
    sleep(1)
    print(user + "-800@yahoo.com")
    sleep(1)
    print(user + "-900@yahoo.com")
    sleep(1)
    print(user + "-1000@yahoo.com")
    sleep(1)
    print(user + "-200@yahoo.com")
    sleep(1)
    print(user + "-3000@yahoo.com")
    sleep(1)
    print(user + "-4000@yahoo.com")
    sleep(1)
    print(user + "-5000@yahoo.com")
    sleep(1)
    print(user + "-6000@yahoo.com")
    sleep(1)
    print(user + "-abc@yahoo.com")
    sleep(1)
    print(user + "-de@yahoo.com")
    sleep(1)
    print(user + "-ae@yahoo.com")
    sleep(1)
    print(user + "_01@yahoo.com")
    sleep(1)
    print(user + "_02@yahoo.com")
    sleep(1)
    print(user + "_ar@yahoo.com")
    sleep(1)
    print(user + "_abc@yahoo.com")
    sleep(1)
    print(user + "_ef@yahoo.com")
    sleep(1)
    print(user + "_ro@yahoo.com")
    sleep(1)
    print(user + "_bn@yahoo.com")
    sleep(1)
    print(user + "_08@yahoo.com")
    sleep(1)
    print(user + "_11@yahoo.com")
    sleep(1)
    print(user + "_12@yahoo.com")
    sleep(1)
    print(user + "_13@yahoo.com")
    sleep(1)
    print(user + "_14@yahoo.com")
    sleep(1)
    print(user + "_15@yahoo.com")
    sleep(1)
    print(user + "_16@yahoo.com")
    sleep(1)
    print(user + "_17@yahoo.com")
    sleep(1)
    print(user + "_18@yahoo.com")
    sleep(1)
    print(user + "_20@yahoo.com")
    sleep(1)
    print(user + "_30@yahoo.com")
    sleep(1)
    print(user + "_40@yahoo.com")
    sleep(1)
    print(user + "_50@yahoo.com")
    sleep(1)
    print(user + "_60@yahoo.com")
    sleep(1)
    print(user + "_100@yahoo.com")
    sleep(1)
    print(user + "_200@yahoo.com")



print("\033[1;32m      ___  ___       ___   _____   _____    _  __    __ ")
print("\033[1;32m     /   |/   |     /   | |_   _| |  _  \  | | \ \  / / ")
print("\033[1;32m    / /|   /| |    / /| |   | |   | |_| |  | |  \ \/ /  ")
print("\033[1;32m   / / |__/ | |   / / | |   | |   |  _  /  | |   }  {   ")
print("\033[1;32m  / /       | |  / /  | |   | |   | | \ \  | |  / /\ \  ")
print("\033[1;32m /_/        |_| /_/   |_|   |_|   |_|  \_\ |_| /_/  \_\ ")
print("                                                                   ")
print("\033[1;91m                                      By Badrddin & Muntathar          ")
print("\033[1;32m                               ===================>>     ")

print("                                                                   ")
print("\033[0;35m [01] Email")
print("                                                 ")
number= input("\033[0;35m [+]Tybe Number :")
if number == ("1"):
    print("                                                               ")
    print("\033[1;91m         _                      _______                      _")
    print("\033[1;91m   _dMMMb._              .adOOOOOOOOOba.              _,dMMMb_")
    print("\033[1;91m  dP'  ~YMMb            dOOOOOOOOOOOOOOOb            aMMP~  `Yb")
    print("\033[1;91m  V      ~+Mb          dOOOOOOOOOOOOOOOOOb          dM+~      V")
    sleep(1)
    print("\033[1;91m           `Mb.       dOOOOOOOOOOOOOOOOOOOb       ,dM'")
    print("\033[1;91m          `YMb._   |OOOOOOOOOOOOOOOOOOOOO|   _,dMP'")
    print("\033[1;91m   __     `YMMM| OP'~+YOOOOOOOOOOOP++`YO |MMMP'     __")
    print("\033[1;91m ,dMMMb.     ~~' OO     `YOOOOOP'     OO `~~     ,dMMMb.")
    print("\033[1;91m ,dP~  `YMba_      OOb      `OOO'      dOO      _aMMP'  ~Yb._")
    print("\033[1;91m<MMP'     `~YMMa_  YOOo @  OOO  @   oOOP   _adMP~'      `YMM>")
    print("\033[1;91m          `YMMMM\`OOOo     OOO     oOOO'/MMMMP'")
    sleep(1)
    print("\033[1;91m   ,aa.     `~YMMb `OOOb._,dOOOb._,dOOO'dMMP~'       ,aa.")
    print("\033[1;91m ,dMYYMba._         `OOOOOOOOOOOOOOOOO'          _,adMYYMb.")
    print("\033[1;91m ,MP'   `YMMba._      OOOOOOOOOOOOOOOOO       _,adMMP'   `YM.")
    sleep(1)
    print("\033[1;91m  MP'        ~YMMMba._ YOOOOPVVVVVYOOOOP  _,adMMMMP~       `YM")
    print("\033[1;91m  YMb           ~YMMMM\`OOOOI`````IOOOOO'/MMMMP~           dMP")
    print("\033[1;91m  `Mb.           `YMMMb`OOOI,,,,,IOOOO'dMMMP'           ,dM'")
    print("\033[1;91m  `'                    `OObNNNNNdOO'                   `'")
    print("\033[1;91m                           `~OOOOO~'   TISSUE")
    sleep(1)
    bad()
else:
    print("\033[1;91m [!] Error Number ")
